import {
  faAlignLeft,
  faAnglesLeft,
  faAnglesRight,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowUp,
  faArrowUpRightFromSquare,
  faBan,
  faBolt,
  faBook,
  faBookOpen,
  faBoxArchive,
  faBoxOpen,
  faBoxesStacked,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faCircleExclamation,
  faCircleInfo,
  faCircleQuestion,
  faClock,
  faCloud,
  faCloudDownloadAlt,
  faCode,
  faCog,
  faCompass,
  faCopy,
  faCube,
  faCubes,
  faDownload,
  faEdit,
  faEllipsisH,
  faExclamationCircle,
  faExclamationTriangle,
  faExternalLinkAlt,
  faFile,
  faFileAlt,
  faFileCircleQuestion,
  faFileCode,
  faFileLines,
  faFilter,
  faFilterCircleXmark,
  faFolder,
  faFolderOpen,
  faFolderPlus,
  faFolderTree,
  faGamepad,
  faGlobe,
  faHardDrive,
  faHashtag,
  faHouse,
  faIdBadge,
  faInfoCircle,
  faLayerGroup,
  faList,
  faLocationCrosshairs,
  faLock,
  faMicrochip,
  faMinus,
  faMobileScreenButton,
  faPause,
  faPauseCircle,
  faPenToSquare,
  faPlay,
  faPlug,
  faPlus,
  faPlusCircle,
  faPuzzlePiece,
  faQuestionCircle,
  faRightToBracket,
  faRotate,
  faRotateLeft,
  faSave,
  faSearch,
  faShieldAlt,
  faShieldHalved,
  faShieldVirus,
  faSignInAlt,
  faSignOutAlt,
  faSliders,
  faSlidersH,
  faSpinner,
  faStar,
  faTag,
  faTerminal,
  faThumbsUp,
  faTimes,
  faToggleOff,
  faToggleOn,
  faTrash,
  faTriangleExclamation,
  faUpload,
  faUser,
  faUserCheck,
  faUserCircle,
  faUserGear,
  faUserSlash,
  faWaveSquare,
  faWrench,
} from '@fortawesome/free-solid-svg-icons';
import { faSquare, faWindowRestore } from '@fortawesome/free-regular-svg-icons';
import { faSteam, faSteamSymbol } from '@fortawesome/free-brands-svg-icons';

export const iconRegistry = {
  alignLeft: faAlignLeft,
  anglesLeft: faAnglesLeft,
  anglesRight: faAnglesRight,
  arrowDown: faArrowDown,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  arrowUp: faArrowUp,
  arrowUpRightFromSquare: faArrowUpRightFromSquare,
  ban: faBan,
  bolt: faBolt,
  book: faBook,
  bookOpen: faBookOpen,
  boxArchive: faBoxArchive,
  boxOpen: faBoxOpen,
  boxesStacked: faBoxesStacked,
  check: faCheck,
  checkCircle: faCheckCircle,
  chevronDown: faChevronDown,
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronUp: faChevronUp,
  circleCheck: faCircleCheck,
  circleExclamation: faCircleExclamation,
  circleInfo: faCircleInfo,
  circleQuestion: faCircleQuestion,
  clock: faClock,
  cloud: faCloud,
  cloudDownloadAlt: faCloudDownloadAlt,
  code: faCode,
  cog: faCog,
  compass: faCompass,
  copy: faCopy,
  cube: faCube,
  cubes: faCubes,
  download: faDownload,
  edit: faEdit,
  ellipsisH: faEllipsisH,
  exclamationCircle: faExclamationCircle,
  exclamationTriangle: faExclamationTriangle,
  externalLinkAlt: faExternalLinkAlt,
  file: faFile,
  fileAlt: faFileAlt,
  fileCircleQuestion: faFileCircleQuestion,
  fileCode: faFileCode,
  fileLines: faFileLines,
  filter: faFilter,
  filterCircleXmark: faFilterCircleXmark,
  folder: faFolder,
  folderOpen: faFolderOpen,
  folderPlus: faFolderPlus,
  folderTree: faFolderTree,
  gamepad: faGamepad,
  globe: faGlobe,
  hardDrive: faHardDrive,
  hashtag: faHashtag,
  house: faHouse,
  idBadge: faIdBadge,
  infoCircle: faInfoCircle,
  layerGroup: faLayerGroup,
  list: faList,
  locationCrosshairs: faLocationCrosshairs,
  lock: faLock,
  microchip: faMicrochip,
  minus: faMinus,
  mobileScreenButton: faMobileScreenButton,
  pause: faPause,
  pauseCircle: faPauseCircle,
  penToSquare: faPenToSquare,
  play: faPlay,
  plug: faPlug,
  plus: faPlus,
  plusCircle: faPlusCircle,
  puzzlePiece: faPuzzlePiece,
  questionCircle: faQuestionCircle,
  rightToBracket: faRightToBracket,
  rotate: faRotate,
  rotateLeft: faRotateLeft,
  save: faSave,
  search: faSearch,
  shieldAlt: faShieldAlt,
  shieldCheck: faShieldHalved,
  shieldExclamation: faShieldVirus,
  shieldHalved: faShieldHalved,
  shieldVirus: faShieldVirus,
  signInAlt: faSignInAlt,
  signOutAlt: faSignOutAlt,
  sliders: faSliders,
  slidersH: faSlidersH,
  syncAlt: faRotate,
  spinner: faSpinner,
  square: faSquare,
  star: faStar,
  steam: faSteam,
  steamSymbol: faSteamSymbol,
  tag: faTag,
  terminal: faTerminal,
  thumbsUp: faThumbsUp,
  times: faTimes,
  toggleOff: faToggleOff,
  toggleOn: faToggleOn,
  trash: faTrash,
  triangleExclamation: faTriangleExclamation,
  upload: faUpload,
  user: faUser,
  userCheck: faUserCheck,
  userCircle: faUserCircle,
  userGear: faUserGear,
  userSlash: faUserSlash,
  waveSquare: faWaveSquare,
  windowRestore: faWindowRestore,
  wrench: faWrench,
} as const;

export type IconName = keyof typeof iconRegistry;

const legacyIconNameMap = Object.keys(iconRegistry).reduce<Record<string, IconName>>(
  (map, iconName) => {
    const legacyToken = `fa-${iconName.replace(/([A-Z])/g, '-$1').toLowerCase()}`;
    map[legacyToken] = iconName as IconName;
    return map;
  },
  {},
);

export function resolveIconName(token: string): IconName {
  if (token in iconRegistry) {
    return token as IconName;
  }

  const legacyTokens = token
    .split(/\s+/)
    .filter((part) => part.startsWith('fa-') && part !== 'fa-spin' && part !== 'fa-pulse');
  const resolvedToken = legacyTokens[legacyTokens.length - 1];
  if (resolvedToken && resolvedToken in legacyIconNameMap) {
    return legacyIconNameMap[resolvedToken];
  }

  throw new Error(`Unknown icon token: ${token}`);
}
